In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('./output/baseline/20Q_gate_Tokyo.csv')
df

,circuit_name,graph_model,depth_ratio,gate_ratio,cx_ratio,opt_method,layout_method,routing_method
0,20Q_gate_Tokyo_large_1_2_1.5_no.8,Tokyo,1.9024,1.3393,1.8507,qiskit:0,sabre,sabre
1,20Q_gate_Tokyo_large_1_2_1.5_no.8,Tokyo,1.4634,0.7381,1.7164,qiskit:1,sabre,sabre
2,20Q_gate_Tokyo_large_1_2_1.5_no.8,Tokyo,1.2683,0.6786,1.5075,qiskit:2,sabre,sabre
3,20Q_gate_Tokyo_large_1_25_1.5_no.1,Tokyo,1.1885,1.0610,1.1531,qiskit:0,sabre,sabre
4,20Q_gate_Tokyo_large_1_25_1.5_no.1,Tokyo,0.8626,0.6268,1.0959,qiskit:1,sabre,sabre
...,...,...,...,...,...,...,...,...
1795,20Q_gate_Tokyo_large_1_3_1.5_no.4,Tokyo,0.9135,0.7833,1.8148,qiskit:1,sabre,sabre
1796,20Q_gate_Tokyo_large_1_3_1.5_no.4,Tokyo,0.7596,0.6601,1.4321,qiskit:2,sabre,sabre
1797,20Q_gate_Tokyo_large_2_0_1.5_no.0,Tokyo,1.4727,1.3451,1.8667,qiskit:0,sabre,sabre
1798,20Q_gate_Tokyo_large_2_0_1.5_no.0,Tokyo,0.6909,0.7168,1.7111,qiskit:1,sabre,sabre
1799,20Q_gate_Tokyo_large_2_0_1.5_no.0,Tokyo,0.5818,0.6283,1.3556,qiskit:2,sabre,sabre

In [4]:
df.describe()

       depth_ratio   gate_ratio     cx_ratio
count  1800.000000  1800.000000  1800.000000
mean      1.339189     0.897219     1.493382
std       0.559363     0.303200     0.352377
min       0.298200     0.433600     0.892500
25%       0.876625     0.636550     1.154600
50%       1.201150     0.784750     1.479450
75%       1.683375     1.212600     1.799325
max       3.592600     1.521700     2.309100

In [6]:
df[df.opt_method == 'qiskit:1']

,circuit_name,graph_model,depth_ratio,gate_ratio,cx_ratio,opt_method,layout_method,routing_method
1,20Q_gate_Tokyo_large_1_2_1.5_no.8,Tokyo,1.4634,0.7381,1.7164,qiskit:1,sabre,sabre
4,20Q_gate_Tokyo_large_1_25_1.5_no.1,Tokyo,0.8626,0.6268,1.0959,qiskit:1,sabre,sabre
7,20Q_gate_Tokyo_large_2_15_1.5_no.5,Tokyo,1.4062,0.8080,1.6555,qiskit:1,sabre,sabre
10,20Q_gate_Tokyo_large_1_0_1.5_no.6,Tokyo,0.7551,0.7699,1.8889,qiskit:1,sabre,sabre
13,20Q_gate_Tokyo_large_2_3_1.5_no.2,Tokyo,1.5102,0.8066,1.7361,qiskit:1,sabre,sabre
...,...,...,...,...,...,...,...,...
1786,20Q_gate_Tokyo_large_2_20_1.5_no.3,Tokyo,1.1808,0.6738,1.2437,qiskit:1,sabre,sabre
1789,20Q_gate_Tokyo_large_1_4_1.5_no.5,Tokyo,1.1884,0.7030,1.3868,qiskit:1,sabre,sabre
1792,20Q_gate_Tokyo_large_1_15_1.5_no.8,Tokyo,0.8525,0.6020,1.0943,qiskit:1,sabre,sabre
1795,20Q_gate_Tokyo_large_1_3_1.5_no.4,Tokyo,0.9135,0.7833,1.8148,qiskit:1,sabre,sabre
1798,20Q_gate_Tokyo_large_2_0_1.5_no.0,Tokyo,0.6909,0.7168,1.7111,qiskit:1,sabre,sabre